name: diffusion
channels:
  - pytorch
  - conda-forge
  - nvidia
  - anaconda
  - defaults
dependencies:
  - python=3.10
  - pytorch
  - pytorch-cuda=12.1
  - pip:
    - jupyter
    - pandas
    - numpy
    - seaborn
    - matplotlib
    - pytorch-lightning
    - scipy
    - tensorboard
    - PyYAML
    - optuna
    - scikit-learn
    - wandb
    - typer
    - line_profiler_pycharm
    - rich
    - omegaconf
    - hydra-core
    - hydra-optuna-sweeper
    - torchinfo
    - pytest
    - albumentations
    - opencv-python
    - ftfy
    - regex
    - numba
    - ipympl
    - ipywidgets
    - torchvision
    - pytorch_toolbelt
    - torcheval
    - moviepy
    - einops
    - rootutils