_target_: diffusion.models.unet.UNetModel
in_channels: 3
model_channels: 64
out_channels: 3
num_res_blocks: 2
dropout: 0.2
attention_resolutions: [2, 4]
channel_mult: [1, 2, 4, 4]

img_key: ${noise_scheduler.img_noised_key}
timesteps_key: ${noise_scheduler.timesteps_key}