type: WrappedUNetModel
kwargs:
    version: "from_improved_ddpm_paper"
    in_channels: 3
    model_channels: 32
    out_channels: 3
    num_res_blocks: 3
    attention_resolutions: 
        - 2
    dropout: 0.3
    channel_mult: 
        - 1
        - 2
        - 4
        - 8
    conv_resample: True
    dims: 2
    num_heads: 2
    num_heads_upsample: -1
