type: WrappedUNetModel
kwargs:
    version: "from_improved_ddpm_paper"
    in_channels: 3
    model_channels: 128
    out_channels: 3
    num_res_blocks: 2
    attention_resolutions: 
        - 16
        - 8
    dropout: 0.3
    channel_mult: 
        - 1
        - 2
        - 2
        - 2
    conv_resample: True
    dims: 2
    num_heads: 4
    num_heads_upsample: -1
