sampler:
  diffusion_steps: 4000

predictors:
  model_dir: WrappedUNetModel-bs128-abs128-llr-4-emaFalse-2024-02-11-03-26-21



output:
  save_all: True
  save_dir: /opt/diffusion/data_dumps/samples/${predictors.model_dir}