
batch_size: 1024
n_imgs: 1000

model_path: WrappedUNetModel-bs128-abs128-llr-4.8-emaTrue-2024-02-17-10-39-45-last-model
dataset_name: cifar10

output:
  save_all: false
  convert_to_gif: false
  save_last: true
  save_dir: /opt/diffusion/data_dumps/samples/${dataset_name}/${model_path}