sampler:
  batch_size: 1024

predictors:
  model_dir: WrappedUNetModel-bs128-abs128-llr-4.8-emaTrue-2024-02-17-22-57-05-last-model



output:
  save_all: false
  save_last: true
  save_dir: /opt/diffusion/data_dumps/samples/${predictors.model_dir}